services:

  orbis-db:
    image: kartoza/postgis:12.4
    environment:
      POSTGRES_USER: orbis
      POSTGRES_PASS: orbis
      POSTGRES_DBNAME: orbis
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5666:5432"
    networks:
      - orbis

  orbis-server:
    build:
      context: .
    tty: true
    environment:
      SYS_ENV: development
      ENABLE_DJANGO: 1
      DJANGO_CLIENT_HOST: http://localhost:3000
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_CELERY_BROKER_HOST: "broker"
      DJANGO_CELERY_BROKER_REDIS_PASSWORD: "itsasecret"
    volumes:
      - ./server:/home/app/server
    ports:
      - "8000:8000"
    networks:
      - orbis
      - orbis-shared

  orbis-client:
    image: node:16.13.1
    tty: true
    environment:
      REACT_APP_API_HOST: http://localhost:8000
      REACT_APP_DOCKER: "true"
      GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
    working_dir: /home/app/client
    volumes:
      - ./client:/home/app/client
    command: bash -c "yarn install && yarn build && yarn start"
    ports:
      - "3000:3000"
      - "35729:35729"
    networks:
      - orbis

  orbis-broker:
    image: "public.ecr.aws/bitnami/redis:6.2"
    environment:
      REDIS_PASSWORD: "itsasecret"
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_EXTRA_FLAGS: "--appendonly no --save \"\""
      REDIS_DISABLE_COMMANDS: "FLUSHALL"
    networks:
      - orbis

  orbis-runner:
    build: .
    environment:
      SYS_ENV: development
      ENABLE_CELERY: 1
      DJANGO_CELERY_BROKER_HOST: "broker"
      DJANGO_CELERY_BROKER_REDIS_PASSWORD: "itsasecret"
    volumes:
      - ./server:/home/app/server
    depends_on:
      - orbis-server
      - orbis-broker
    networks:
      - orbis
      - orbis-shared

networks:
  # 2 networks: 
  #  one for communication among services defined in _this_ docker-compose file, 
  #  one for communication among services defined in in _different_ docker-compose files.
  orbis:
    name: orbis
    driver: bridge
  orbis-shared:
    name: orbis-shared
    driver: bridge
    attachable: true
