version: "3.5"

services:
  db:
    image: kartoza/postgis:11.0-2.5
    environment:
      POSTGRES_USER: orbis
      POSTGRES_PASS: orbis
      POSTGRES_DBNAME: orbis
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5666:5432"
    networks:
      - orbis

  server:
    build:
      context: .
      dockerfile: Dockerfile.artifact
      args:
        TOKEN: "${GITHUB_REGISTRY_TOKEN}"
    tty: true
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      PIPENV_NOSPIN: 1
      GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
    ports:
      - "80:80"
    networks:
      - orbis

networks:
  orbis:
    driver: bridge
