version: "3.5"

services:
  db:
    image: kartoza/postgis:11.0-2.5
    environment:
      POSTGRES_USER: orbis
      POSTGRES_PASS: orbis
      POSTGRES_DBNAME: orbis
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5666:5432"
    networks:
      - orbis

  server:
    build:
      context: .
      args:
        TOKEN: "${GITHUB_REGISTRY_TOKEN}"
    tty: true
    environment:
      PIPENV_NOSPIN: 1
      PIPENV_DONT_LOAD_ENV: 1
      DJANGO_SETTINGS_MODULE: core.settings
      GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
      DOCKER_BUILDKIT: 1
      DJANGO_CLIENT_HOST: http://localhost:3000
    volumes:
      - ./server:/home/app/server
      - ./client:/home/app/client
    ports:
      - "8000:8000"
    networks:
      - orbis

  client:
    image: node:12.13.1
    tty: true
    environment:
      REACT_APP_API_HOST: http://localhost:8000
      REACT_APP_DOCKER: "true"
      GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
      DOCKER_BUILDKIT: 1
    working_dir: /home/app/client
    volumes:
      - ./client:/home/app/client
    command: bash -c "yarn install && yarn build && yarn start"
    ports:
      - "3000:3000"
      - "35729:35729"
    networks:
      - orbis

networks:
  orbis:
    driver: bridge
