version: "2"

services:
  db:
    image: kartoza/postgis:12.4
    environment:
      POSTGRES_USER: orbis
      POSTGRES_PASS: orbis
      POSTGRES_DBNAME: orbis
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5666:5432"
    networks:
      - orbis

  server:
    build:
      context: .
      dockerfile: Dockerfile.server.deployment
      args:
        TOKEN: "${GITHUB_REGISTRY_TOKEN}"
        TYPE: server
    tty: true
    environment:
      DJANGO_APP: orbis
      DJANGO_ENVIRONMENT: local
      DJANGO_INSTANCE: local
      ENABLE_UWSGI: 1
      DJANGO_SETTINGS_MODULE: core.settings
      PIPENV_NOSPIN: 1
      PIPENV_DONT_LOAD_ENV: 1
      GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
      DJANGO_DB_USER: orbis
      DJANGO_DB_PASSWORD: orbis
      DJANGO_DB_NAME: orbis
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_CLIENT_HOST: ${CLIENT_HOST}

    ports:
      - "8000:80"
    networks:
      - orbis

  client:
    build:
      context: .
      dockerfile: Dockerfile.client.deployment
      args:
        TOKEN: "${GITHUB_REGISTRY_TOKEN}"
        TYPE: client
    tty: true
    environment:
      REACT_APP_DOCKER: "true"
      REACT_APP_API_HOST: ${API_HOST}
      GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
    ports:
      - "3000:80"
    networks:
      - orbis

networks:
  orbis:
    driver: bridge
