version: "3.5"

services:
  db:
    image: kartoza/postgis:11.0-2.5
    environment:
      POSTGRES_USER: orbis
      POSTGRES_PASS: orbis
      POSTGRES_DBNAME: orbis
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5666:5432"
    networks:
      - orbis

  server:
    build:
      context: .
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PIPENV_NOSPIN=1
      - GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
    ports:
      - "8000:80"
    networks:
      - orbis

  # client:
  #   image: node:10.16.3
  #   environment:
  #     NODE_ENV: "development"
  #     GITHUB_REGISTRY_TOKEN: "${GITHUB_REGISTRY_TOKEN}"
  #   working_dir: /opt/orbis/client
  #   volumes:
  #     - ./client:/opt/orbis/client
  #   command: bash -c "yarn install && yarn build && yarn start"
  #   tty: true
  #   ports:
  #     - "3000:3000"
  #     - "35729:35729"
  #   networks:
  #     - orbis

networks:
  orbis:
    driver: bridge
