# Generated by Django 2.2 on 2020-01-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
