# Generated by Django 3.2.12 on 2022-02-14 09:02

from django.db import migrations


def create_admin_groups(apps, schema_editor):

    ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    CustomerUserModel = apps.get_model("astrosat_users", "CustomerUser")
    PermissionModel = apps.get_model("auth", "Permission")
    GroupModel = apps.get_model("auth", "Group")

    # admin_group...
    group, _ = GroupModel.objects.get_or_create(name="AdminGroup")

    # core_admin_group (w/ permissions)...
    content_type = ContentTypeModel.objects.get_for_model(CustomerUserModel)
    permission, _ = PermissionModel.objects.get_or_create(
        codename="can_register_customer_user",
        name="Can Register CustomerUser",
        content_type=content_type,
    )
    group, _ = GroupModel.objects.get_or_create(name="CoreAdminGroup")
    group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_bookmark'),
    ]

    operations = [
        migrations.RunPython(
            create_admin_groups, reverse_code=migrations.RunPython.noop
        )
    ]

