# Generated by Django 3.2.4 on 2021-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of geometry type e.g. oa, lsoa, msoa, lad', max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Order of the geometry's specificity")),
            ],
            options={
                'verbose_name': 'Geometry Type',
                'verbose_name_plural': 'Geometry Types',
                'ordering': ['order'],
            },
        ),
    ]
