# Generated by Django 3.2.4 on 2021-07-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0002_satellites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satelliteresult',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='satellitesearch',
            name='tiers',
        ),
        migrations.DeleteModel(
            name='SatelliteTier',
        ),
    ]
