# Generated by Django 3.2.4 on 2021-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0003_remove_satellitetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='adapter_name',
            field=models.CharField(default='sentinel-2', help_text='The name of the adapter that contains the specific query fns used by this Satellite', max_length=64),
            preserve_default=False,
        ),
    ]
