# Generated by Django 3.2.4 on 2021-07-21 10:41

from django.db import migrations, models
import django.db.models.deletion
import satellites.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0028_usermessages'),
        ('satellites', '0004_satellite_adapter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteDataSource',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('satellite_id', models.SlugField()),
                ('scene_id', models.SlugField()),
                ('visualisation_id', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Satellite DataSources',
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='satelliteresult',
            options={
                'verbose_name': 'Satellite Result',
                'verbose_name_plural': 'Satellite Results'
            },
        ),
        migrations.AlterModelOptions(
            name='satellitesearch',
            options={
                'ordering': ['-created'],
                'verbose_name': 'Satellite Search',
                'verbose_name_plural': 'Satellites Searches'
            },
        ),
        migrations.RemoveConstraint(
            model_name='satellitesearch',
            name='unique_owner_name',
        ),
        migrations.RemoveField(
            model_name='satelliteresult',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='satellitesearch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='satellitesearch',
            name='owner',
        ),
        migrations.AlterField(
            model_name='satellitesearch',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='satellitesearch',
            name='satellites',
            field=models.ManyToManyField(to='satellites.Satellite'),
        ),
        migrations.AlterField(
            model_name='satellitevisualisation',
            name='thumbnail',
            field=models.FileField(
                blank=True,
                help_text='A thumbnail image representing this visualisation.',
                null=True,
                upload_to=satellites.models.models_satellites.
                visualisation_thumbnail_path
            ),
        ),
        migrations.AddField(
            model_name='satellitedatasource',
            name='customer_user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='satelite_data_sources',
                to='astrosat_users.customeruser'
            ),
        ),
        migrations.AddConstraint(
            model_name='satellitedatasource',
            constraint=models.UniqueConstraint(
                fields=('name', 'customer_user'),
                name='unique_name_per_customer_user'
            ),
        ),
    ]
