# Generated by Django 3.2.4 on 2021-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0005_auto_20210721_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satellitedatasource',
            options={
                'ordering': ['created'],
                'verbose_name': 'Satellite DataSource',
                'verbose_name_plural': 'Satellite DataSources'
            },
        ),
        migrations.AlterModelOptions(
            name='satellitesearch',
            options={
                'ordering': ['-created'],
                'verbose_name': 'Satellite Search',
                'verbose_name_plural': 'Satellite Searches'
            },
        ),
        migrations.AlterField(
            model_name='satellitedatasource',
            name='satellite_id',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='satellitedatasource',
            name='scene_id',
            field=models.SlugField(max_length=512),
        ),
        migrations.AlterField(
            model_name='satellitedatasource',
            name='visualisation_id',
            field=models.SlugField(max_length=128),
        ),
    ]
