# Generated by Django 3.2.6 on 2021-09-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0061_datastorage'),
        ('satellites', '0007_satellitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitedatasource',
            name='data_storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellite_source', to='orbis.datastorage'),
        ),
    ]
