# Generated by Django 3.2.9 on 2021-11-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0029_customer_vat_number'),
        ('satellites', '0008_satellitedatasource_data_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitedatasource',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_data_sources', to='astrosat_users.customeruser'),
        ),
    ]
