# Generated by Django 3.2.10 on 2021-12-14 12:04

from django.db import migrations, models
import django.db.models.deletion
import orbis.models.models_storage


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0071_datastorage_status'),
        ('astrosat_users', '0029_customer_vat_number'),
        ('satellites', '0009_alter_satellitedatasource_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satellitedatasource',
            options={'verbose_name': 'Satellite DataSource', 'verbose_name_plural': 'Satellite DataSources'},
        ),
        migrations.RemoveConstraint(
            model_name='satellitedatasource',
            name='unique_name_per_customer_user',
        ),
        migrations.RemoveField(
            model_name='satellitedatasource',
            name='is_active',
        ),
        migrations.AddField(
            model_name='satellitedatasource',
            name='categories',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of categories that this DataSource belongs to.', validators=[orbis.models.models_storage.validate_data_source_categories]),
        ),
        migrations.AddField(
            model_name='satellitedatasource',
            name='orbs',
            field=models.JSONField(blank=True, default=list, help_text='List of orbs that this DataSource belong to.', validators=[orbis.models.models_storage.validate_data_source_orbs]),
        ),
        migrations.AddField(
            model_name='satellitedatasource',
            name='type',
            field=models.CharField(choices=[('raster', 'raster'), ('vector', 'vector')], default='raster', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='satellitedatasource',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='astrosat_users.customeruser'),
        ),
        migrations.AlterField(
            model_name='satellitedatasource',
            name='data_storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_source', to='orbis.datastorage'),
        ),
    ]
