# Generated by Django 3.2.10 on 2021-12-14 12:05

from django.db import migrations


def update_satellite_data_sources(apps, schema_editor):
    SatelliteDataSourceModel = apps.get_model(
        "satellites", "SatelliteDataSource"
    )

    for satellite_data_source in SatelliteDataSourceModel.objects.all():
        owner = satellite_data_source.customer_user.user
        satellite_data_source.orbs = [{
            "name": "My Data",
            "description": f"Saved data for {owner.username}."
        }]
        satellite_data_source.categories = {"name": "Satellite Images"}
        satellite_data_source.type = "raster"
        satellite_data_source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0010_auto_20211214_1204'),
    ]

    operations = [
        migrations.RunPython(
            update_satellite_data_sources,
            reverse_code=migrations.RunPython.noop
        ),
    ]
