# Generated by Django 3.2.4 on 2021-06-11 22:58

from django.db import migrations, models
import proxy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=128)),
                ('namespace', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('proxy_url', models.URLField()),
                ('proxy_method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], max_length=16)),
                ('proxy_params', models.JSONField(blank=True, help_text='A dictionary of all the parameters to pass to the proxy_url (including any authentication tokens)', null=True, validators=[proxy.models.validate_proxy_params])),
                ('adapter_name', models.CharField(help_text='The name of the adapter that contains the specific fns used by this ProxyDataSource', max_length=64)),
            ],
            options={
                'verbose_name': 'Proxy Data Source',
                'verbose_name_plural': 'Proxy Data Sources',
            },
        ),
        migrations.AddConstraint(
            model_name='proxydatasource',
            constraint=models.UniqueConstraint(fields=('authority', 'namespace', 'name', 'version'), name='unique_proxy_data_source_id'),
        ),
    ]
