# Generated by Django 3.2.4 on 2021-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_proxydatasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxydatasource',
            name='proxy_authentication_password',
            field=models.CharField(blank=True, help_text='The authentication password (for Basic Authentication).', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='proxydatasource',
            name='proxy_authentication_token',
            field=models.CharField(blank=True, help_text='The authentication token (for Bearer or ApiKey Authentication).', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='proxydatasource',
            name='proxy_authentication_type',
            field=models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('BEARER', 'Bearer'), ('APIKEY', 'Apikey'), ('URL_PARAM', 'Url Param')], help_text='The type of authentication to implement. (Note that if URL_PARAM is selected, it is assumed that the authentication token appears in proxy_params.)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='proxydatasource',
            name='proxy_authentication_username',
            field=models.CharField(blank=True, help_text='The authentication username (for Basic Authentication).', max_length=256, null=True),
        ),
    ]
