# Generated by Django 3.2.9 on 2021-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0007_alter_proxydatasource_proxy_authentication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxydatasource',
            name='request_strategy',
            field=models.TextField(choices=[('STORED_PARAMS_ONLY', 'Stored Params Only'), ('REQUEST_ONLY', 'Request Only')], default='STORED_PARAMS_ONLY'),
        ),
    ]
