# Generated by Django 3.2.12 on 2022-02-16 21:28

from django.db import migrations, models
import proxy.models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0009_alter_proxydatasource_proxy_authentication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxydatasource',
            name='proxy_extra_content',
            field=models.FileField(blank=True, help_text='A file w/ extra information to use as needed by the adapter. Typically this will be JSON or GeoJSON, but the adapter will process it as needed.', null=True, upload_to=proxy.models.proxy_extra_content_path),
        ),
    ]
