# Generated by Django 3.2.12 on 2022-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0010_proxydatasource_proxy_extra_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxydatasource',
            name='request_strategy',
            field=models.TextField(choices=[('STORED_PARAMS_ONLY', 'Stored Params Only'), ('REQUEST_ONLY', 'Request Only'), ('MERGED_PARAMS', 'Merged Params')], default='STORED_PARAMS_ONLY'),
        ),
    ]
