# Generated by Django 2.2 on 2019-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0003_orbisuserprofile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbisuserprofile',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='Has this user been onboarded'),
        ),
        migrations.AddField(
            model_name='orbisuserprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('Europe', 'Europe'), ('Africa', 'Africa'), ('Central Asia', 'Central Asia'), ('East Asia', 'East Asia'), ('Western Asia', 'Western Asia'), ('Southern Asia', 'Southern Asia'), ('South East Asia', 'South East Asia'), ('Oceania', 'Oceania'), ('North America', 'North America'), ('Central America & Caribbean', 'Central America & Caribbean'), ('South America', 'South America'), ('Arctic', 'Arctic'), ('Antartica', 'Antartica'), ('Oceans & seas', 'Oceans & seas')], help_text='The default region for this user', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='orbisuserprofile',
            name='units',
            field=models.CharField(choices=[('Imperial', 'Imperial'), ('Metric', 'Metric')], default='Imperial', help_text='The default units for this user', max_length=256),
        ),
    ]
