# Generated by Django 2.2 on 2019-12-19 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrosat_users', '0004_auto_20191202_1100'),
        ('orbis', '0004_auto_20191210_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('authority', models.CharField(default='*', max_length=128)),
                ('namespace', models.CharField(default='*', max_length=128)),
                ('name', models.CharField(default='*', max_length=128)),
                ('version', models.CharField(default='*', max_length=128)),
            ],
            options={
                'verbose_name': 'Orbis Data Scope',
                'verbose_name_plural': 'Orbis Data Scopes',
            },
        ),
        migrations.CreateModel(
            name='DataScopeRoleAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True)),
                ('create', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('data_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbis.DataScope')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrosat_users.UserRole')),
            ],
        ),
        migrations.CreateModel(
            name='DataScopeOwnerAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True)),
                ('create', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('data_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbis.DataScope')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datascope',
            name='owners',
            field=models.ManyToManyField(related_name='data_scopes', through='orbis.DataScopeOwnerAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datascope',
            name='roles',
            field=models.ManyToManyField(related_name='data_scopes', through='orbis.DataScopeRoleAccess', to='astrosat_users.UserRole'),
        ),
        migrations.AddConstraint(
            model_name='datascope',
            constraint=models.UniqueConstraint(fields=('authority', 'namespace', 'name', 'version'), name='unique_source_id'),
        ),
    ]
