# Generated by Django 2.2 on 2020-01-14 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0006_auto_20200103_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbisSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_token_timeout', models.IntegerField(default=60, help_text='The time (in minutes) that the data_token is valid for', validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Orbis Settings',
                'verbose_name_plural': 'Orbis Settings',
            },
        ),
    ]
