# Generated by Django 2.2 on 2020-03-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0009_orbissatellites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satelliteresult',
            name='thumbnail',
        ),
    ]
