# Generated by Django 2.2 on 2020-03-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0010_remove_satelliteresult_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='A unique name for the tier.', unique=True)),
                ('title', models.CharField(help_text='A pretty display name for the tier.', max_length=128)),
                ('description', models.TextField(blank=True, help_text='A description of the tier.', null=True)),
                ('order', models.IntegerField(default=1, help_text='The order to render this tier.')),
            ],
            options={
                'verbose_name': 'Satellite Tier',
                'verbose_name_plural': 'Satellite Tiers',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='resolutions',
        ),
        migrations.RemoveField(
            model_name='satellitesearch',
            name='resolutions',
        ),
        migrations.DeleteModel(
            name='SatelliteResolution',
        ),
        migrations.AddField(
            model_name='satelliteresult',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='orbis.SatelliteTier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellitesearch',
            name='tiers',
            field=models.ManyToManyField(related_name='searches', to='orbis.SatelliteTier'),
        ),
    ]
