# Generated by Django 2.2 on 2020-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0011_auto_20200309_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitesearch',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='satellitesearch',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
