# Generated by Django 2.2 on 2020-03-16 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0013_auto_20200313_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbissettings',
            name='maximum_aoi_area',
            field=models.FloatField(default=500, help_text='The maximum area (in kilometres) that can be used as a query argument.', validators=[django.core.validators.MaxValueValidator(500000000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orbissettings',
            name='data_token_timeout',
            field=models.IntegerField(default=60, help_text='The time (in minutes) that the data_token is valid for.', validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)]),
        ),
    ]
