# Generated by Django 2.2 on 2020-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0014_auto_20200316_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteresult',
            name='scene_id',
            field=models.SlugField(help_text='A unique id for the scene.', max_length=256),
        ),
    ]
