# Generated by Django 3.0.5 on 2020-05-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0016_default_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owneraccess',
            options={'verbose_name': 'Owner Access', 'verbose_name_plural': 'Owner Access <em>(please save the DataSource prior to adding OwnerAccess instances)</em>'},
        ),
        migrations.AlterModelOptions(
            name='roleaccess',
            options={'verbose_name': 'Role Access', 'verbose_name_plural': 'Role Access <em>(please save the DataSource prior to adding RoleAccess instances)</em>'},
        ),
    ]
