# Generated by Django 3.0.7 on 2020-06-24 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orbis.models.models_orbs
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0008_auto_20200612_1021'),
        ('orbis', '0017_auto_20200508_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('access', models.PositiveIntegerField(default=orbis.models.models_orbs.Access['READ'], validators=[django.core.validators.MaxValueValidator(7)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='Orb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Orb',
                'verbose_name_plural': 'Orbs',
            },
        ),
        migrations.RemoveField(
            model_name='owneraccess',
            name='data_scope',
        ),
        migrations.RemoveField(
            model_name='owneraccess',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='roleaccess',
            name='data_scope',
        ),
        migrations.RemoveField(
            model_name='roleaccess',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='datascope',
            options={'verbose_name': 'Data Scope', 'verbose_name_plural': 'Data Scopes'},
        ),
        migrations.RemoveConstraint(
            model_name='datascope',
            name='unique_source_id',
        ),
        migrations.RemoveField(
            model_name='datascope',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='datascope',
            name='roles',
        ),
        migrations.AddConstraint(
            model_name='datascope',
            constraint=models.UniqueConstraint(fields=('authority', 'namespace', 'name', 'version'), name='unique_source_id_pattern'),
        ),
        migrations.DeleteModel(
            name='OwnerAccess',
        ),
        migrations.DeleteModel(
            name='RoleAccess',
        ),
        migrations.AddField(
            model_name='license',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='astrosat_users.Customer'),
        ),
        migrations.AddField(
            model_name='license',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='astrosat_users.CustomerUser'),
        ),
        migrations.AddField(
            model_name='license',
            name='orb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='orbis.Orb'),
        ),
        migrations.AddField(
            model_name='datascope',
            name='orb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_scopes', to='orbis.Orb'),
        ),
    ]
