# Generated by Django 3.0.7 on 2020-06-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0018_auto_20200624_1205'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('orb', 'customer', 'customer_user'), name='unique_license_orb_customer_user'),
        ),
    ]
