# Generated by Django 3.0.7 on 2020-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0019_auto_20200624_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datascope',
            name='orb',
        ),
        migrations.AddField(
            model_name='datascope',
            name='orbs',
            field=models.ManyToManyField(related_name='data_scopes', to='orbis.Orb'),
        ),
    ]
