# Generated by Django 3.0.8 on 2020-07-09 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orbis.models.models_orbs
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0014_reset_customers'),
        ('orbis', '0020_auto_20200624_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('access', models.PositiveIntegerField(default=orbis.models.models_orbs.Access['READ'], validators=[django.core.validators.MaxValueValidator(7)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='astrosat_users.Customer')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licences', to='astrosat_users.CustomerUser')),
                ('orb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='orbis.Orb')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
            },
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.UniqueConstraint(fields=('orb', 'customer', 'customer_user'), name='unique_licence_orb_customer_user'),
        ),
    ]
