# Generated by Django 3.0.8 on 2020-07-14 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0022_auto_20200714_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licence',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
