# Generated by Django 3.0.8 on 2020-07-17 11:58

from django.db import migrations


# data migration to ensure that all existing CustomerUsers
# have a licence for the "core" Orb


def create_core_licences(apps, schema_editor):
    CustomerModel = apps.get_model("astrosat_users", "Customer")
    LicenceModel = apps.get_model("orbis", "Licence")
    OrbModel = apps.get_model("orbis", "Orb")

    # create the core Orb and it's DataScope as needed...
    core_orb = OrbModel.get_core_orb()

    for customer in CustomerModel.objects.all():
        for customer_user in customer.customer_users.all():
            LicenceModel.objects.get_or_create(
                orb=core_orb,
                customer=customer,
                customer_user=customer_user,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0023_auto_20200714_1546'),
    ]

    operations = [
        migrations.RunPython(
            create_core_licences, reverse_code=migrations.RunPython.noop
        ),
    ]
