# Generated by Django 3.1 on 2020-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0026_auto_20200815_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='orb',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Every CustomerUser is granted a Licence to the core Orb.'),
        ),
        migrations.AddField(
            model_name='orb',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Licences to a private Orb are hidden from CustomerUsers.'),
        ),
        migrations.AddConstraint(
            model_name='orb',
            constraint=models.UniqueConstraint(condition=models.Q(is_core=True), fields=('is_core',), name='only_one_core_orb'),
        ),
    ]
