# Generated by Django 3.1.1 on 2020-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0028_licencedcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orb',
            name='is_private',
        ),
        migrations.AddField(
            model_name='orb',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Licences to a hidden Orb are not shown to CustomerUsers.'),
        ),
    ]
