# Generated by Django 3.1.2 on 2020-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0029_auto_20200907_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='orb',
            name='licence_cost',
            field=models.FloatField(default=0, help_text='The cost of a single licence to this Orb.'),
        ),
    ]
