# Generated by Django 3.1.3 on 2020-11-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0031_orders'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orb',
            name='only_one_core_orb',
        ),
        migrations.RemoveField(
            model_name='orb',
            name='is_core',
        ),
    ]
