# Generated by Django 3.1.7 on 2021-03-24 08:28

from django.db import migrations, models
import orbis.models.models_documents


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0032_remove_core_orb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=orbis.models.models_documents.privacy_media_path, validators=[orbis.models.models_documents.validate_pdf_extension])),
            ],
            options={
                'verbose_name': 'Privacy Document',
                'verbose_name_plural': 'Documents: Privacy',
            },
        ),
        migrations.CreateModel(
            name='TermsDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=orbis.models.models_documents.terms_media_path, validators=[orbis.models.models_documents.validate_pdf_extension])),
            ],
            options={
                'verbose_name': 'Terms Document',
                'verbose_name_plural': 'Documents: Terms',
            },
        ),
    ]
