# Generated by Django 3.1.7 on 2021-03-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0034_terms_document_agreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_form',
            new_name='report',
        ),
    ]
