# Generated by Django 3.1.7 on 2021-03-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0035_auto_20210330_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsdocumentagreement',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='order',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orbis.termsdocument'),
        ),
    ]
