# Generated by Django 3.1.7 on 2021-04-08 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0036_auto_20210330_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascope',
            name='applications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, help_text='An optional array of applications that this DataScope derives its data from', size=None),
        ),
    ]
