# Generated by Django 3.1.7 on 2021-04-12 11:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0038_auto_20210409_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascope',
            name='applications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, help_text='An optional array of applications that this DataScope derives its data from', size=None),
        ),
    ]
