# Generated by Django 3.2.2 on 2021-05-13 09:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0042_auto_20210427_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbisUserFeedbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('source_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), help_text='An array of source_ids that prompted feedback in this instance.', size=None)),
                ('provided_feedback', models.BooleanField(default=False, help_text='Did the user provide feedback?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_records', to='orbis.orbisuserprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
