# Generated by Django 3.2.2 on 2021-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0044_orb_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orb',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Licences to default Orbs are automatically granted upon registration.'),
        ),
    ]
