# Generated by Django 3.2.4 on 2021-06-04 10:29

import astrosat.utils.utils_db
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0027_auto_20210422_1525'),
        ('orbis', '0045_orb_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=functools.partial(astrosat.utils.utils_db.CONDITIONAL_CASCADE, *(), **{'condition': {'orb__is_default': True}, 'default_value': None}), related_name='licences', to='astrosat_users.customeruser'),
        ),
    ]
