# Generated by Django 3.2.4 on 2021-06-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0046_alter_licence_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometrySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of dataset type e.g. oa, lsoa, msoa, lad', max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Order of the dataset type's specificity")),
            ],
            options={
                'verbose_name': 'GeometrySet Type',
                'verbose_name_plural': 'GeometrySet Types',
                'ordering': ['order'],
            },
        ),
    ]
