# Generated by Django 3.2.4 on 2021-06-09 19:00

from django.db import migrations
from django.db.migrations import migration

from orbis.models import GeometrySet

GEOMETRY_SET_NAMES = ["oa", "lsoa", "msoa", "lad"]


def add_geometry_set(apps, schema_editor):
    """ Add default geometry set """
    model = apps.get_model("orbis", "GeometrySet")
    for i, name in enumerate(GEOMETRY_SET_NAMES):
        model.objects.get_or_create(name=name, defaults={"order": i})


def remove_geometry_set(apps, schema_editor):
    """ Remove default geometry set """
    model = apps.get_model("orbis", "GeometrySet")
    for name in GEOMETRY_SET_NAMES:
        try:
            model.objects.get(name=name).delete()
        except model.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0047_geometryset'),
    ]

    operations = [migrations.RunPython(add_geometry_set, remove_geometry_set)]
