# Generated by Django 3.2.4 on 2021-06-09 19:00

from django.db import migrations
from django.db.migrations import migration

from orbis.models import GeometrySet

geometry_sets = ["oa", "lsoa", "msoa", "lad"]


def add_geometry_set(apps, schema_editor):
    """ Add default geometry set """
    [
        GeometrySet(name=name, order=index + 1).save() for index,
        name in enumerate(geometry_sets)
    ]


def remove_geometry_set(apps, schema_editor):
    """ Remove default geometry set """
    [GeometrySet.objects.get(name=item).delete() for item in geometry_sets]


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0047_geometryset'),
    ]

    operations = [migrations.RunPython(add_geometry_set, remove_geometry_set)]
