# Generated by Django 3.2.4 on 2021-06-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0048_auto_20210609_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satelliteresult',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='satelliteresult',
            name='satellite',
        ),
        migrations.RemoveField(
            model_name='satelliteresult',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='satellitesearch',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='satellitesearch',
            name='satellites',
        ),
        migrations.RemoveField(
            model_name='satellitesearch',
            name='tiers',
        ),
        migrations.DeleteModel(
            name='Satellite',
        ),
        migrations.DeleteModel(
            name='SatelliteResult',
        ),
        migrations.DeleteModel(
            name='SatelliteSearch',
        ),
        migrations.DeleteModel(
            name='SatelliteTier',
        ),
        migrations.DeleteModel(
            name='SatelliteVisualisation',
        ),
    ]
