# Generated by Django 3.2.4 on 2021-07-23 10:38

from django.db import migrations, models
import orbis.models.models_orbs


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0049_removesatellites'),
    ]

    operations = [
        migrations.AddField(
            model_name='orb',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features that this orb supports.', validators=[orbis.models.models_orbs.validate_orb_features]),
        ),
    ]
