# Generated by Django 3.2.5 on 2021-07-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0050_orb_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orbissettings',
            name='maximum_aoi_area',
        ),
    ]
