# Generated by Django 3.2.5 on 2021-08-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0051_remove_orbissettings_maximum_aoi_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='orb',
            name='short_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
