# Generated by Django 3.2.6 on 2021-08-17 13:30

import django.core.validators
from django.db import migrations, models
import orbis.models.models_orbs


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0054_orb_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orb',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=orbis.models.models_orbs.orb_logo_path, validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
