# Generated by Django 3.2.6 on 2021-09-06 11:06

# data migration to automatically copy over existing document instances to new db models

from django.db import migrations

from orbis.models.models_documents import DocumentAgreement, PrivacyDocument


def copy_documents(apps, schema_editor):

    UserGuideDocumentModel = apps.get_model("orbis", "UserGuideDocument")
    PrivacyDocumentModel = apps.get_model("orbis", "PrivacyDocument")
    TermsDocumentModel = apps.get_model("orbis", "TermsDocument")
    DocumentModel = apps.get_model("orbis", "Document")
    DocumentAgreementModel = apps.get_model("orbis", "DocumentAgreement")

    for user_guide_document in UserGuideDocumentModel.objects.all():
        document, _ = DocumentModel.objects.get_or_create(
            name=user_guide_document.name,
            version=user_guide_document.version,
            is_active=user_guide_document.is_active,
            type="GUIDE"
        )

    for privacy_document in PrivacyDocumentModel.objects.all():
        document, _ = DocumentModel.objects.get_or_create(
            name=privacy_document.name,
            version=privacy_document.version,
            is_active=privacy_document.is_active,
            type="PRIVACY"
        )

    for terms_document in TermsDocumentModel.objects.all():
        document, _ = DocumentModel.objects.get_or_create(
            name=terms_document.name,
            version=terms_document.version,
            is_active=terms_document.is_active,
            type="TERMS"
        )
        for terms_agreement in terms_document.terms_agreements.all():
            agreement, _ = DocumentAgreementModel.objects.get_or_create(
                document=document,
                user=terms_agreement.user,
            )
            agreement.timestamp = terms_agreement.timestamp
            agreement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0056_orbis_documents'),
    ]

    operations = [
        migrations.RunPython(
            copy_documents, reverse_code=migrations.RunPython.noop
        ),
    ]
