# Generated by Django 3.2.6 on 2021-09-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0057_orbis_documents_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orb',
            name='terms_document',
        ),
    ]
