# Generated by Django 3.2.6 on 2021-09-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0058_remove_orb_terms_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyDocument',
        ),
        migrations.RemoveField(
            model_name='termsdocument',
            name='users',
        ),
        migrations.RemoveField(
            model_name='termsdocumentagreement',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='termsdocumentagreement',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGuideDocument',
        ),
        migrations.RemoveField(
            model_name='order',
            name='terms',
        ),
        migrations.DeleteModel(
            name='TermsDocument',
        ),
        migrations.DeleteModel(
            name='TermsDocumentAgreement',
        ),
    ]
