# Generated by Django 3.2.6 on 2021-09-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0059_auto_20210914_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='orb',
            name='is_exclusive',
            field=models.BooleanField(default=False, help_text='Licences to exclusive Orbs are automatically removed when licences to other orbs are assigned; they cannot co-exist.'),
        ),
    ]
