# Generated by Django 3.2.6 on 2021-09-16 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0028_usermessages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orbis', '0060_orb_is_exclusive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/Name of the data stored', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the Data object was created')),
                ('size', models.FloatField(default=0.0, help_text='Size of the data in MBs')),
                ('customer', models.ForeignKey(help_text="The customer that 'owns' this data storage object.", on_delete=django.db.models.deletion.CASCADE, to='astrosat_users.customer')),
                ('user', models.ForeignKey(help_text='The user that created this data storage object', on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Storage',
                'verbose_name_plural': 'Data Storage',
            },
        ),
    ]
