# Generated by Django 3.2.6 on 2021-09-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0061_datastorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
