# Generated by Django 3.2.8 on 2021-10-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0063_document_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_type_name_orb_active',
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_type_name_active',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('type', 'name', 'orb'), name='unique_type_name_orb_active'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('orb', None)), fields=('type', 'name'), name='unique_type_name_active'),
        ),
    ]
