# Generated by Django 3.2.8 on 2021-10-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0065_update_document_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
