# Generated by Django 3.2.8 on 2021-11-19 09:01

from django.db import migrations, models
import orbis.models.models_users


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0067_orb_can_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbisuserprofile',
            name='orb_state',
            field=models.JSONField(blank=True, default=dict, validators=[orbis.models.models_users.validate_orb_state]),
        ),
        migrations.AlterField(
            model_name='orbisuserprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('EUROPE', 'Europe'), ('AFRICA', 'Africa'), ('CENTRAL_ASIA', 'Central Asia'), ('EAST_ASIA', 'East Asia'), ('WEST_ASIA', 'Western Asia'), ('SOUTH_ASIA', 'Southern Asia'), ('SOUTH_EAST_ASIA', 'South East Asia'), ('OCEANIA', 'Oceania'), ('NORTH_AMERICA', 'North America'), ('CENTRAL_AMERICA_CARIBBEAN', 'Central America & Caribbean'), ('SOUTH_AMERICA', 'South America'), ('ARCTIC', 'Arctic'), ('ANTARCTICA', 'Antartica'), ('OCEANS_SEAS', 'Oceans & seas')], help_text='The default region for this user', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orbisuserprofile',
            name='units',
            field=models.CharField(choices=[('IMPERIAL', 'Imperial'), ('METRIC', 'Metric')], default='IMPERIAL', help_text='The default units for this user', max_length=256),
        ),
    ]
