# Generated by Django 3.2.9 on 2021-11-19 16:45

from django.db import migrations, models
import orbis.models.models_orbs


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0068_orbisuserprofile_orbstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orb',
            name='default_orb_state',
            field=models.JSONField(blank=True, default=dict, help_text='State to be passed to a user when they are assigned a licence to this Orb.', validators=[orbis.models.models_orbs.validate_default_orb_state]),
        ),
    ]
