# Generated by Django 3.2.9 on 2021-11-25 14:18

from django.db import migrations


def migrate_orbis_profile_units(apps, schema_editor):
    OrbisUserProfileModel = apps.get_model("orbis", "OrbisUserProfile")

    for profile in OrbisUserProfileModel.objects.all():
        profile.units = profile.units.upper()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0069_orb_default_orb_state'),
    ]

    operations = [
        migrations.RunPython(
            migrate_orbis_profile_units, reverse_code=migrations.RunPython.noop
        ),
    ]
