# Generated by Django 3.2.10 on 2021-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0070_orbisprofile_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16),
        ),
    ]
