# Generated by Django 3.2.16 on 2022-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbis', '0071_datastorage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometryset',
            name='description',
            field=models.TextField(blank=True, help_text='A description of what the GeometrySet name means.', null=True),
        ),
    ]
