export { ReactComponent as Cleaning } from './cleaning.svg';
export { ReactComponent as Clothing } from './clothing.svg';
export { ReactComponent as Food } from './food.svg';
export { ReactComponent as Medical } from './medical-equipment-aids.svg';
export { ReactComponent as Other } from './other.svg';
export { ReactComponent as PPE } from './ppe.svg';
export { ReactComponent as Services } from './service.svg';
export { ReactComponent as Staffing } from './staffing.svg';
export { ReactComponent as Stationery } from './stationery.svg';
