from .serializers_customers import CustomerSerializer, CustomerUserSerializer
from .serializers_documents import DocumentAgreementSerializer, DocumentSerializer
from .serializers_orbs import OrbSerializer
from .serializers_orders import OrderSerializer
from .serializers_users import OrbisUserProfileSerializer, OrbisUserFeedbackRecordSerializer, OrbisUserSerializer
from .serializers_auth import LoginSerializer, RegisterSerializer
from .serializers_storage import DataStorageSerializer
