# Generated by Django 2.2 on 2020-01-15 14:32

import astrosat_users.models.models_users
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import maps.models.models_bookmarks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A pretty display name for the bookmark', max_length=128)),
                ('description', models.TextField(blank=True, help_text='A description of the bookmark', null=True)),
                ('feature_collection', django.contrib.postgres.fields.jsonb.JSONField(help_text='a GeoJSON description of the data being bookmarked.', validators=[maps.models.models_bookmarks.validate_feature_collection])),
                ('center', django.contrib.gis.db.models.fields.PointField(help_text='The center point of this bookmark on the map', srid=4326)),
                ('zoom', models.FloatField(help_text='The zoom level of the bookmark on the map.')),
                ('owner', models.ForeignKey(on_delete=models.SET(astrosat_users.models.models_users.get_sentinel_user), related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'title')},
            },
        ),
    ]
