# Generated by Django 2.2 on 2020-01-16 12:46

import astrosat_users.models.models_users
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import maps.models.models_bookmarks
import maps.storage


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='A thumbnail image representing this bookmark.', null=True, storage=maps.storage.S3Storage(), upload_to=maps.models.models_bookmarks.bookmark_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(help_text='The center point of this bookmark on the map.', srid=4326),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the bookmark.', null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='feature_collection',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='a GeoJSON description of the data being bookmarked.', null=True, validators=[maps.models.models_bookmarks.validate_feature_collection]),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(help_text='The owner of this bookmark.', on_delete=models.SET(astrosat_users.models.models_users.get_sentinel_user), related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(help_text='A pretty display name for the bookmark.', max_length=128),
        ),
    ]
