# Generated by Django 2.2 on 2020-01-29 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200116_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
