# Generated by Django 2.2 on 2020-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20200129_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the bookmark was first created.'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When the bookmark was last modified.'),
        ),
    ]
