# Generated by Django 2.2 on 2020-01-31 12:34

from django.db import migrations, models
import maps.models.models_bookmarks


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20200129_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='A thumbnail image representing this bookmark.', null=True, upload_to=maps.models.models_bookmarks.bookmark_thumbnail_path),
        ),
    ]
