# Generated by Django 2.2 on 2020-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_satellites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satellitevisualisation',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='satellitevisualisation',
            name='order',
            field=models.IntegerField(default=1, help_text='The order to render the visualisation.'),
        ),
    ]
