# Generated by Django 2.2 on 2020-02-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20200204_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellitescene',
            name='satellite',
        ),
        migrations.DeleteModel(
            name='SatelliteVisualisation',
        ),
        migrations.DeleteModel(
            name='Satellite',
        ),
        migrations.DeleteModel(
            name='SatelliteScene',
        ),
    ]
