# Generated by Django 3.1 on 2020-08-15 07:08

from django.db import migrations, models
import maps.models.models_bookmarks


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20200723_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='feature_collection',
            field=models.JSONField(blank=True, help_text='a GeoJSON description of the annotations on the map.', null=True, validators=[maps.models.models_bookmarks.validate_feature_collection]),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='layers',
            field=models.JSONField(blank=True, help_text='A list of all the source_ids of the data layers loaded on the map.', null=True, validators=[maps.models.models_bookmarks.validate_layers]),
        ),
    ]
