# Generated by Django 3.1.5 on 2021-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20200815_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='orbs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
