# Generated by Django 3.2.9 on 2021-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_aois'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='data_source',
            field=models.CharField(default='', help_text='DataSource AOI instance is associated with', max_length=128),
        ),
    ]
