# Generated by Django 3.2.12 on 2022-05-04 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import maps.models.models_map_styles


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0031_auto_20220406_1246'),
        ('maps', '0016_aoi_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMapStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='The API key for the map style.', max_length=255, null=True)),
                ('customer', models.ForeignKey(help_text='The customer that uses this map style.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_map_styles', to='astrosat_users.customer')),
            ],
            options={
                'verbose_name': 'Customer Map Style',
                'verbose_name_plural': 'Customer Map Styles',
            },
        ),
        migrations.CreateModel(
            name='MapStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the map style.', max_length=255, unique=True)),
                ('style', models.FileField(help_text='The style file to use for the map.', upload_to=maps.models.models_map_styles.map_styles_path, validators=[django.core.validators.FileExtensionValidator(['json'])])),
                ('thumbnail', models.FileField(help_text='Thumbnail of the map style.', upload_to=maps.models.models_map_styles.map_styles_path)),
                ('customers', models.ManyToManyField(help_text='The customer that uses this map style.', related_name='map_styles', through='maps.CustomerMapStyle', to='astrosat_users.Customer')),
            ],
            options={
                'verbose_name': 'Map Style',
                'verbose_name_plural': 'Map Styles',
            },
        ),
        migrations.AddField(
            model_name='customermapstyle',
            name='map_style',
            field=models.ForeignKey(help_text='The map style that the customer uses.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_map_styles', to='maps.mapstyle'),
        ),
    ]
