# Generated by Django 3.2.12 on 2022-08-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_mapstyles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstyle',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default map style.'),
        ),
    ]
