# Generated by Django 3.2.12 on 2022-04-10 01:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import orbs.eco_an_alba.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eco_an_alba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the proposal', max_length=64)),
                ('description', models.TextField(blank=True, help_text='Description of the proposal', null=True)),
                ('proposal_description', models.TextField(blank=True, help_text='Description of the work being proposed', null=True)),
                ('proposal_start_date', models.DateTimeField(blank=True, help_text='Start date of the proposal', null=True)),
                ('proposal_end_date', models.DateTimeField(blank=True, help_text='End date of the proposal', null=True)),
                ('proposal_activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, help_text='Activities associated with the proposal', null=True, size=None)),
                ('report_state', models.JSONField(blank=True, help_text='JSON representation of the impact assessment report associated with the proposal', null=True, validators=[orbs.eco_an_alba.models.validate_report_state])),
                ('owner', models.ForeignKey(help_text='Owner of the proposal', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ('-proposal_start_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner'),
        ),
    ]
