name: "Chromatic"

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: client
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        working-directory: client
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ee7d59d7c137
