name: PR Deploy

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy-to-testing:
    name: Deploy to Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: Request a Deployment for this PR
        run: |
          set -eu

          # Used to query for PRs associated with the commit
          export GITHUB_TOKEN="${{ secrets.ASTROSAT_GITHUB_CREATE_DEPLOYMENT_TOKEN }}"

          set -x

          cd scripts/create-deployment
          yarn install

          REPO_OWNER="$(dirname "$GITHUB_REPOSITORY")"
          REPO_NAME="$(basename "$GITHUB_REPOSITORY")"

          node createDeployment.js \
            --environment testing \
            --repo-owner "$REPO_OWNER" \
            --repo-name "$REPO_NAME" \
            deploy-pr \
            --pull-request "${{ github.event.pull_request.number }}"
