name: BUILD

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy-to-testing:
    name: Deploy to Testing
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: Setup dependencies
        run: ./scripts/ci-setup-deps.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Deployment
        run: |
          set -eu

          # Used to query for PRs associated with the commit
          export GITHUB_TOKEN="${{ github.token }}"

          # Required for createDeployment.js to use the AWS profiles defined by ci-setup-deps.sh
          export AWS_SDK_LOAD_CONFIG=1

          set -x

          cd scripts/create-deployment
          yarn install

          REPO_OWNER="$(dirname "$GITHUB_REPOSITORY")"
          REPO_NAME="$(basename "$GITHUB_REPOSITORY")"

          node createDeployment.js \
            --environment testing \
            --repo-owner "$REPO_OWNER" \
            --repo-name "$REPO_NAME" \
            deploy-pr \
            --pull-request "${{ github.event.pull_request.number }}"
