name: RELEASE

on: deployment

jobs:
  release:
    name: Build Releasable Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: frontend-build-${{ hashFiles('**/client/yarn.lock') }}
          restore-keys: |
            frontend-build-
      - name: Build Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd client
          yarn install
          yarn release
